### ISSUE TITLE
Marker Interfaces for indexing strategies

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-pdo-adapter#4]
While trying the pdo adapter I ran into an issue due to a wrong indexing strategy used by the adapter.
I wanted to use `pdo_pgsql` but did not configure the indexing strategy so the factory used the MySql indexing strategy as a default.

I got a syntax error:

```
Fatal error: Uncaught Prooph\EventStore\Adapter\Exception\RuntimeException: Error during createSchemaFor: 42601; 7; ERROR:  syntax error at or near "`"
LINE 1: CREATE TABLE `_878c0b7e51ecaab95c511fc816ad2a70c9418208` (
                     ^ in /var/www/html/vendor/prooph/event-store-pdo-adapter/src/PDOEventStoreAdapter.php:354
```

We should either remove the default to force the user to set a strategy or mark the strategies with vendor specific interfaces so that the PdoAdapter can check if an indexing strategy is used that can work together with the used database vendor.

**Comment by prolic** [comment]
done by eb2094a147d4fb78bfac32f57583dabf678fac1b
